### ISSUE TITLE
entering thre backslashes produces an error

### ISSUE THREAD

**Issue by englishextra** [oss6/kamil#1]
> Timestamp: 25.05.2016 21:53:33
> Error: SyntaxError: \ at end of pattern
> Source File: http://oss6.github.io/kamil/kamil.js
> Line: 20

**Comment by oss6** [comment]
Thank you very much. I will look into that and push the fixes by the end of the weekend (overwhelmed by exams XD).

**Comment by oss6** [comment]
Ok, released version 0.1.1 with the fix. The problem was regex escaping.

**Comment by englishextra** [comment]
It's all right now. Good product.
